
spring:
  # 数据库配置
  datasource:    
    url: dbc:mysql://192.168.2.241:3306/preedu?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: develop
    password: top123456

    
    # 对联结池进行配置 确保联结池不会假死
    hikari:
      idle-timeout: 280000
      validation-timeout: 3000
      connection-test-query: SELECT 1 FROM DUAL
      max-lifetime: 300000
      maximum-pool-size: 35
      
  
  jpa:
    hibernate:
      ddl-auto: update


# 日志配置
logging:
  level:
    root: info
    org.hibernate.SQL: debug

